apiVersion: v1
kind: ServiceAccount
metadata:
  name: friendsaccount
---
apiVersion: v1
kind: Service
metadata:
  name: consul-apps-user-friends
spec:
  selector:
    app: consul-apps-user-friends
  ports:
    - port: 8080
      targetPort: 8080
  #externalName: consul-apps-user-friends.service.consul
  #type: ExternalName
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: consul-apps-user-friends
#spec:
#  externalName: consul-apps-user-friends.service.consul
#  type: ExternalName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consul-apps-user-friends
  name: consul-apps-user-friends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-apps-user-friends
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: consul-apps-user-friends
    spec:
      containers:
        - name: consul-apps-user-friends
          image: consul-apps/user-friends:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
