apiVersion: v1
kind: ServiceAccount
metadata:
  name: videoaccount
---
apiVersion: v1
kind: Service
metadata:
  name: consul-apps-user-video
spec:
  selector:
    app: consul-apps-user-video
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-apps-user-video
  labels:
    app: consul-apps-user-video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-apps-user-video
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
        #'consul.hashicorp.com/transparent-proxy-overwrite-probes': 'true'
      labels:
        app: consul-apps-user-video
    spec:
      containers:
        - name: consul-apps-user-video
          image: consul-apps/user-video:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          args: ["-Dspring.cloud.consul.discovery.prefer-ip-address=true"]
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
